# Generated by debtap
# Maintainer: Markus Näther <naetherm@informatik.uni-freiburg.de>
# Maintainer: Olaf Leidinger <oleid@mescharet.de>

pkgname=rock-dkms-git
pkgver=2.6.22
_pkgver=2.6-22
pkgrel=1
pkgdesc="Linux AMD GPU kernel driver from ROC in DKMS format."
arch=('any')
url=""
license=('GPL')
groups=('')
depends=('dkms>=1.95')
backup=('etc/modprobe.d/blacklist-radeon.conf')
options=('!strip' '!emptydirs')

source=("http://repo.radeon.com/rocm/apt/debian/pool/main/r/rock-dkms/rock-dkms_${_pkgver}_all.deb")
sha512sums=('46172d4c0d22dd33199b92faf703c99278827ba16d14d1d5d32aa9aa774e3216466737ccf26672b4d9f5837edfe965d095b95a32dc6a98e817bb6901905b0723')

package(){
	tar xf data.tar.xz -C "${pkgdir}"

	install -D -m644 "${pkgdir}/usr/share/doc/rock-dkms/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
