# Generated by debtap
# Maintainer: Markus Näther <naetherm@informatik.uni-freiburg.de>
# Maintainer: Olaf Leidinger <oleid@mescharet.de>

pkgname=rock-dkms-git
pkgver=2.3.14
_pkgver=2.3-14
pkgrel=2
pkgdesc="Linux AMD GPU kernel driver from ROC in DKMS format."
arch=('any')
url=""
license=('GPL')
groups=('')
depends=('dkms>=1.95')
backup=('etc/modprobe.d/blacklist-radeon.conf')
options=('!strip' '!emptydirs')

source=("http://repo.radeon.com/rocm/apt/debian/pool/main/r/rock-dkms/rock-dkms_${_pkgver}_all.deb")
sha512sums=('7094428a187f83ff55871b067c27d483e150cb79cafd3de6ac283fc2816b15de54f46524865e68e9aa550d7412e1a07bf390b9082c15c5340bc308d2a9ea4b70')

package(){
	tar xf data.tar.xz -C "${pkgdir}"

	install -D -m644 "${pkgdir}/usr/share/doc/rock-dkms/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
