--- Makefile.orig	2020-03-19 19:01:11.000000000 +0100
+++ Makefile	2020-04-13 16:57:05.856296717 +0200
@@ -25,7 +25,7 @@
 OS_VERSION = "0.0"
 endif
 
-ifneq ($(findstring $(OS_NAME), "ubuntu" "sled" "sles" "opensuse" "opensuse-leap" "amzn" "custom-rhel" "fedora"),)
+ifneq ($(findstring $(OS_NAME), "ubuntu" "sled" "sles" "opensuse" "opensuse-leap" "amzn" "custom-rhel" "fedora" "arch"),)
 DRM_VER=$(shell sed -n 's/^VERSION = \(.*\)/\1/p' $(kdir)/Makefile)
 DRM_PATCH=$(shell sed -n 's/^PATCHLEVEL = \(.*\)/\1/p' $(kdir)/Makefile)
 else ifeq ("debian", $(OS_NAME))
@@ -63,6 +63,8 @@
 subdir-ccflags-y += -DOS_NAME_AMZ
 else ifeq ("debian",$(OS_NAME))
 subdir-ccflags-y += -DOS_NAME_DEBIAN
+else ifeq ("arch",$(OS_NAME))
+subdir-ccflags-y += -DOS_NAME_ARCH
 else
 subdir-ccflags-y += -DOS_NAME_UNKNOWN
 endif
