# Generated by debtap
# Maintainer: Olaf Leidinger <oleid@mescharet.de>

pkgname=rock-dkms
pkgver=1.8.151
_pkgver=1.8-151
pkgrel=2
pkgdesc="Linux AMD GPU kernel driver from ROC in DKMS format."
arch=('any')
url=""
license=('GPL')
groups=('')
depends=('dkms>=1.95')
backup=('etc/modprobe.d/blacklist-radeon.conf')
options=('!strip' '!emptydirs')

source=("http://repo.radeon.com/rocm/apt/debian/pool/main/r/rock-dkms/rock-dkms_${_pkgver}_all.deb"
	"https://github.com/oleid/amdgpu-dkms/commit/7d11254249da86c987601b7d8a1860e12efabefa.patch")
sha512sums=(
	'c3fc094c44bb5d2a21c5f18e24429a5720eed729669f9347308cec48f4c78335732e72acf3db4cb646dd4441160f6bc3531f650c213d67c5584c50b5028e2a53'
	'SKIP')

package(){
	tar xf data.tar.xz -C "${pkgdir}"

	install -D -m644 "${pkgdir}/usr/share/doc/rock-dkms/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

	# patching for >=4.14 - 4.16 (at least) compatibility

	cd ${pkgdir}/usr/src/amdgpu-${_pkgver}
        patch -p1 < "${srcdir}/7d11254249da86c987601b7d8a1860e12efabefa.patch"
}
